Repository XengShi/materialYouNewTab, pull requests merged in 2025-07, with the labels that each got.

#698 Fix analog clock hand rotation
  scripts/clock.js
Labels: ready to merge, bug fixes, refactor, chrome-tested, firefox-tested

#707 (NEW) Updated Japanese translation
  CHANGELOG.md
  README.md
  locales/en.js
  locales/ja.js
  style.css
Labels: ready to merge, i18n / l10n

#699 Animate authorName in quotes
  .github/pull_request_template.md
  index.html
  locales/de.js
  scripts/ai-tools.js
  scripts/bookmarks.js
  scripts/languages.js
  scripts/quotes.js
  scripts/shortcuts.js
  scripts/weather.js
  style.css
  svgs/andakar.svg
  svgs/bing.svg
  svgs/brave.svg
  svgs/defaultWeather.svg
  svgs/duck.svg
  svgs/feels.svg
  svgs/github-shortcut.svg
  svgs/google.svg
  svgs/humidity.svg
  svgs/location.svg
  svgs/offline.svg
  svgs/rounder.svg
  svgs/searchIcon.svg
  svgs/shortcuts_icons/adobe-firefly.svg
  svgs/shortcuts_icons/bard.svg
  svgs/shortcuts_icons/chatgpt.svg
  svgs/shortcuts_icons/email.svg
  svgs/shortcuts_icons/facebook.svg
  svgs/shortcuts_icons/feedback.svg
  svgs/shortcuts_icons/github.svg
  svgs/shortcuts_icons/instagram.svg
  svgs/shortcuts_icons/invalid-url.svg
  svgs/shortcuts_icons/reddit.svg
  svgs/shortcuts_icons/telegram.svg
  svgs/shortcuts_icons/twitter.svg
  svgs/shortcuts_icons/whatsApp.svg
  svgs/shortcuts_icons/youtube.svg
  svgs/starishShape.svg
  svgs/theme.svg
  svgs/tick.svg
  svgs/x.svg
  svgs/youtube.svg
Labels: ready to merge, bug fixes, refactor, ui, chrome-tested, firefox-tested

#703 Update bookmark
  scripts/bookmarks.js
  style.css
Labels: ready to merge, enhancement, ui, chrome-tested, firefox-tested

#709 Made host permissions optional
  CHANGELOG.md
  index.html
  manifest.json
  scripts/search-suggestions.js
Labels: ready to merge, refactor, chrome-tested

#708 Fix: Flash of Default Blue on Page Load
  CHANGELOG.md
  index.html
  scripts/script.js
  scripts/shortcuts.js
  scripts/theme.js
Labels: bug fixes

#718 Optimize date and greetings rendering
  scripts/clock.js
Labels: bug fixes

#719 Added feature edit todo-list
  CHANGELOG.md
  scripts/todo-list.js
  style.css
  svgs/todo-edit-do.svg
  svgs/todo-edit-done.svg
Labels: ready to merge, enhancement
