Repository XengShi/materialYouNewTab, pull requests merged in 2025-02, with the labels that each got.

#508 Moved Dark theme css to style.css
  index.html
  scripts/script.js
  style.css
Labels: ready to merge, refactor

#513 Update for Turkish language support
  README.md
  locales/tr.js
  scripts/languages.js
Labels: ready to merge, i18n / l10n

#514 Update IDN Translation
  locales/idn.js
Labels: ready to merge, i18n / l10n

#515 Fix restore wallpaper bug
  manifest(firefox).json
  manifest.json
  scripts/backup-restore.js
Labels: ready to merge, bug fixes

#516 New translations added for French Language
  locales/fr.js
Labels: ready to merge, i18n / l10n

#518 l10n: Update Czech translation strings
  locales/cs.js
Labels: ready to merge, i18n / l10n

#528 Favicon enhancement
  favicon/icon128.png
  favicon/icon16.png
  favicon/icon48.png
  index.html
  manifest(firefox).json
  manifest.json
  scripts/script.js
  svgs/location.svg
Labels: enhancement, refactor

#523 Seperated `Shortcuts` code, Removed Instagram and Added Discord
  index.html
  scripts/menu-shortcut-page.js
  scripts/script.js
  scripts/shortcuts.js
  style.css
Labels: ready to merge, refactor

#529 Update date format for `ja` and `ko`
  scripts/clock.js
Labels: ready to merge, i18n / l10n

#533 Better weather icons
  scripts/weather.js
Labels: ready to merge, enhancement

#531 Seperated Proxy and Search Suggestions from `script.js`
  index.html
  scripts/revert-extension-icon.js
  scripts/script.js
  scripts/search-suggestions.js
Labels: ready to merge, refactor

#535 Added Feature Hide Whole Weather Section to give more customization
  index.html
  locales/en.js
  scripts/languages.js
  scripts/weather.js
  style.css
Labels: ready to merge, enhancement

#536 Add background color to Edit Shortcuts List
  manifest(firefox).json
  manifest.json
  scripts/shortcuts.js
  style.css
Labels: ready to merge, bug fixes, ui

#539 Fixing Security Vulnerability for shortcuts
  scripts/shortcuts.js
Labels: ready to merge, bug fixes

#511 Added Throttle in Color Picker input for performance optimization
  scripts/script.js
Labels: ready to merge, bug fixes

#540 Minor changes in weather.js code
  scripts/clock.js
  scripts/languages.js
  scripts/shortcuts.js
  scripts/todo-list.js
  scripts/wallpaper.js
  scripts/weather.js
Labels: ready to merge, refactor

#541 Option to edit bookmark name and url
  index.html
  locales/en.js
  scripts/bookmarks.js
  scripts/languages.js
  scripts/script.js
  style.css
Labels: ready to merge, enhancement

#542 Translations for latest new strings (hi, bn, mr)
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  locales/mr.js
  scripts/languages.js
  scripts/save-load-states.js
Labels: ready to merge, i18n / l10n

#543 l10n: Update Czech translation
  locales/cs.js
Labels: ready to merge, i18n / l10n

#544 Add DeepSeek to the list of AI Tools, Remove Firefly
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  locales/mr.js
  scripts/languages.js
Labels: ready to merge, enhancement

#548 New language: Urdu
  README.md
  index.html
  locales/en.js
  locales/ur.js
  manifest(firefox).json
  manifest.json
  scripts/clock.js
  scripts/languages.js
  scripts/weather.js
  style.css
  tools/languagesAnalysis.html
Labels: enhancement, i18n / l10n

#538 Update PageNotFound page
  docs/PageNotFound.html
Labels: docs

#545 Replaced alert and confirm dialog box with custom modal
  index.html
  locales/en.js
  locales/hi.js
  scripts/alert-modal.js
  scripts/backup-restore.js
  scripts/bookmarks.js
  scripts/languages.js
  scripts/script.js
  scripts/search-suggestions.js
  scripts/wallpaper.js
  style.css
Labels: enhancement, ui
