Repository XengShi/materialYouNewTab, pull requests merged in 2025-04, with the labels that each got.

#582 Create CHANGELOG.md
  CHANGELOG.md
Labels: ready to merge, docs

#612 Translation updated
  locales/pt.js
Labels: ready to merge, i18n / l10n

#614 l10n: Update Czech
  locales/cs.js
Labels: ready to merge, i18n / l10n

#617 Updated Italian
  locales/it.js
Labels: ready to merge, i18n / l10n

#616 Fix Fahrenheit Display
  scripts/weather.js
Labels: ready to merge, bug fixes

#594 Update Firefox branch wrt main
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/general_question.yaml
  .github/pull_request_template.md
  .gitignore
  README.md
  docs/Get_WeatherAPI_Key.html
  docs/PageNotFound.html
  docs/feedback.html
  index.html
  locales/az.js
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/es.js
  locales/fr.js
  locales/hi.js
  locales/hu.js
  locales/idn.js
  locales/it.js
  locales/ja.js
  locales/ko.js
  locales/mr.js
  locales/np.js
  locales/pt.js
  locales/ru.js
  locales/sl.js
  locales/tr.js
  locales/ur.js
  locales/uz.js
  locales/vi.js
  locales/zh.js
  locales/zh_TW.js
  scripts/bookmarks.js
  scripts/browser-utils.js
  scripts/clock.js
  scripts/languages.js
  scripts/revert-extension-icon.js
  scripts/script.js
  scripts/search-suggestions.js
  scripts/search.js
  scripts/weather.js
  style.css
  tools/languagesAnalysis.html
Labels: ready to merge, non main branch

#609 Added Location Suggestion Feature
  index.html
  scripts/revert-extension-icon.js
  scripts/weather.js
  style.css
Labels: ready to merge, enhancement

#615 Option to show Minimun-Maximum temperature instead of Feels like
  index.html
  locales/en.js
  locales/hi.js
  scripts/languages.js
  scripts/weather.js
Labels: ready to merge, enhancement

#624 Added Grok and Qwen AI, and Option to choose which AI shortcuts to display
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  locales/mr.js
  scripts/ai-tools.js
  scripts/languages.js
  style.css
Labels: enhancement, ui

#623 Update IDN Translations
  locales/idn.js
Labels: ready to merge, i18n / l10n

#622 Update Bangla translation and changelog
  .github/pull_request_template.md
  CHANGELOG.md
  docs/PageNotFound.html
  locales/bn.js
  scripts/README.md
  scripts/shortcuts.js
Labels: ready to merge, i18n / l10n, docs

#621 l10n: Update Czech
  locales/cs.js
  scripts/weather.js
Labels: ready to merge, i18n / l10n

#625 l10n: Update Czech
  CHANGELOG.md
  locales/cs.js
Labels: ready to merge, i18n / l10n

#626 Update Bengali translations
  CHANGELOG.md
  docs/Get_WeatherAPI_Key.html
  index.html
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/hi.js
  manifest(firefox).json
  manifest.json
  scripts/languages.js
  scripts/search-suggestions.js
  style.css
Labels: ready to merge, i18n / l10n, docs

#627 Update IDN Translations (Fixes and Consistency included)
  locales/idn.js
Labels: ready to merge, i18n / l10n

#628 pt-br language update
  locales/pt.js
Labels: i18n / l10n

#633 Update traditional Chinese translation
  README.md
  locales/zh_TW.js
Labels: ready to merge, i18n / l10n
