Repository XengShi/materialYouNewTab, pull requests merged in 2025-06, with the labels that each got.

#653 Fix feelsLike element Padding for RTL
  locales/fa.js
  scripts/languages.js
  style.css
Labels: ready to merge, bug fixes, ui

#657 Added confirmation alert before resetting shortcuts
  locales/bn.js
  locales/en.js
  locales/fa.js
  locales/hi.js
  scripts/shortcuts.js
Labels: ready to merge, enhancement, i18n / l10n

#659 Add Arabic language
  CHANGELOG.md
  README.md
  index.html
  locales/ar_SA.js
  scripts/clock.js
  scripts/languages.js
  scripts/weather.js
  tools/languagesAnalysis.html
Labels: changes required, i18n / l10n

#660 Transparency effect if wallpaper is set
  index.html
  scripts/wallpaper.js
  style.css
Labels: ui

#679 Added instructions for Zen Browser to README
  README.md
Labels: ready to merge, docs

#685 Add toggle to hide/show location in weather UI
  index.html
  scripts/weather.js
  svgs/location-hide.svg
  svgs/location-show.svg
Labels: ready to merge, enhancement, ui

#686 Tamil language specific
  CHANGELOG.md
  README.md
  index.html
  locales/ta.js
  scripts/clock.js
  scripts/languages.js
  scripts/weather.js
  style.css
  tools/languagesAnalysis.html
Labels: i18n / l10n, ui

#683 Multilingual quotes support
  CHANGELOG.md
  index.html
  privacy-policy.html
  scripts/quotes.js
Labels: ready to merge, enhancement, refactor

#690 Fix greetings/date flickering
  scripts/clock.js
Labels: ready to merge, bug fixes

#692 Updated IDN Translation
  locales/idn.js
Labels: ready to merge, i18n / l10n, chrome-tested

#695 Refactor Shortcuts and Add Reordering Functionality
  README.md
  index.html
  locales/bn.js
  locales/hi.js
  manifest(firefox).json
  manifest.json
  scripts/shortcuts.js
  style.css
Labels: ready to merge, enhancement, refactor, chrome-tested, firefox-tested
