Repository XengShi/materialYouNewTab, pull requests merged in 2025-03, with the labels that each got.

#479 Added Browser's default search engine
  index.html
  locales/bn.js
  locales/en.js
  locales/es.js
  locales/hi.js
  locales/idn.js
  locales/ja.js
  locales/mr.js
  locales/uz.js
  locales/vi.js
  manifest(firefox).json
  manifest.json
  scripts/languages.js
  scripts/script.js
  scripts/search-suggestions.js
  style.css
Labels: ready to merge, enhancement

#550 l10n: Update Czech translation
  locales/cs.js
Labels: ready to merge, i18n / l10n

#551 Update translation : hi, bn, mr
  locales/bn.js
  locales/en.js
  locales/hi.js
  locales/mr.js
  locales/ur.js
Labels: ready to merge, i18n / l10n

#552 Update IDN Translation
  locales/idn.js
Labels: ready to merge, i18n / l10n

#553 Update traditional chinese translation
  locales/zh_TW.js
Labels: ready to merge, i18n / l10n

#554 Fix security warnings
  scripts/backup-restore.js
  scripts/bookmarks.js
  scripts/google-apps.js
  scripts/revert-extension-icon.js
  scripts/save-load-states.js
  scripts/script.js
  scripts/search-suggestions.js
Labels: ready to merge, bug fixes, refactor

#555 New french translations
  locales/fr.js
Labels: ready to merge, i18n / l10n

#558 Fixed google menu icon alignment and Changed Switch button design
  index.html
  style.css
Labels: ready to merge, bug fixes, ui

#559 [Fix]Search radio button hide delay
  style.css
Labels: ready to merge, bug fixes, ui

#560 Changed GPS button to toggle
  index.html
  locales/en.js
  scripts/alert-modal.js
  scripts/languages.js
  scripts/search-suggestions.js
  scripts/wallpaper.js
  scripts/weather.js
  style.css
Labels: ready to merge, enhancement, ui

#561 Improved PR Template and Added Updated Issues Templates (Bug Report, Feature Request, General Question/Help Needed) with Contact Links
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/general_question.yaml
  .github/pull_request_template.md
  README.md
  locales/np.js
  style.css
Labels: ready to merge, docs

#565 Fix Feature Request Template
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: ready to merge, bug fixes, docs

#566 New french translations
  locales/fr.js
Labels: ready to merge, i18n / l10n

#567 Update IDN Translation
  locales/idn.js
Labels: ready to merge, i18n / l10n

#568 PT-BR TRANSLATION
  locales/pt.js
Labels: ready to merge, i18n / l10n

#569 Translation: hindi and bangla, and CSS redundant delete
  locales/bn.js
  locales/hi.js
  manifest(firefox).json
  scripts/script.js
  style.css
Labels: ready to merge, bug fixes, i18n / l10n

#571 Added option for sorting by date added in bookmarks #398
  index.html
  locales/en.js
  scripts/bookmarks.js
  scripts/languages.js
  style.css
Labels: ready to merge, enhancement

#570 Motivational Quotes feature in main branch
  README.md
  index.html
  locales/en.js
  scripts/custom-text.js
  scripts/languages.js
  scripts/quotes.js
  scripts/script.js
  scripts/wallpaper.js
  style.css
Labels: enhancement, docs, ui

#572 l10n: Update Czech translation
  locales/cs.js
Labels: ready to merge, i18n / l10n

#573 Update IDN Translations
  locales/idn.js
Labels: ready to merge, i18n / l10n

#474 Search mode categorization
  .gitignore
  index.html
  locales/en.js
  locales/hi.js
  manifest(firefox).json
  manifest.json
  scripts/languages.js
  scripts/script.js
  scripts/search-suggestions.js
  style.css
Labels: enhancement

#574 v3.1
  README.md
  index.html
  locales/en.js
  manifest(firefox).json
  manifest.json
  style.css
Labels: ready to merge

#578 Update IDN Translations
  locales/idn.js
Labels: ready to merge, i18n / l10n

#580 Removed all extra strings from locales
  README.md
  locales/az.js
  locales/bn.js
  locales/es.js
  locales/fr.js
  locales/hi.js
  locales/hu.js
  locales/idn.js
  locales/it.js
  locales/ja.js
  locales/ko.js
  locales/mr.js
  locales/np.js
  locales/ru.js
  locales/sl.js
  locales/tr.js
  locales/ur.js
  locales/uz.js
  locales/vi.js
  locales/zh.js
  locales/zh_TW.js
Labels: ready to merge, i18n / l10n

#581 Update Translations: Hindi and Bengali
  locales/bn.js
  locales/en.js
  locales/hi.js
  scripts/bookmarks.js
  scripts/search.js
Labels: ready to merge, i18n / l10n, refactor

#583 Update russian translation.
  locales/ru.js
Labels: ready to merge, i18n / l10n

#586 I10n: Update French translations with new search modes and motivational quotes
  locales/fr.js
Labels: ready to merge, i18n / l10n

#585 Some changes to Tips and bug fixes
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  scripts/languages.js
  scripts/revert-extension-icon.js
  scripts/script.js
  scripts/search.js
  style.css
Labels: ready to merge, bug fixes, i18n / l10n, refactor, ui

#592 Fix weather details sometimes failed to display
  index.html
  scripts/languages.js
  scripts/weather.js
Labels: ready to merge, bug fixes

#593 Added Reddit and Quora as Search Platforms
  index.html
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/hi.js
  locales/it.js
  locales/mr.js
  locales/pt.js
  locales/ru.js
  locales/tr.js
  locales/vi.js
  manifest(firefox).json
  manifest.json
  scripts/languages.js
  scripts/search-suggestions.js
  scripts/search.js
Labels: enhancement

#597 Update IDN Translations
  locales/idn.js
Labels: ready to merge, i18n / l10n

#599 Added clock hide option
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  scripts/clock.js
  scripts/languages.js
  style.css
Labels: enhancement, ui

#598 Some changes to hide weather and quotes
  index.html
  scripts/browser-utils.js
  scripts/script.js
  scripts/weather.js
  style.css
Labels: changes required, ui
