Repository XengShi/materialYouNewTab, pull requests merged in 2025-01, with the labels that each got.

#331 Added GPS based location option
  index.html
  languages.js
  locales/bn.js
  locales/en.js
  locales/hi.js
  script.js
Labels: ready to merge, enhancement

#401 Languages Enchantmets
  locales/az.js
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/es.js
  locales/fr.js
  locales/hi.js
  locales/idn.js
  locales/it.js
  locales/ja.js
  locales/ko.js
  locales/mr.js
  locales/pt.js
  locales/ru.js
  locales/sl.js
  locales/tr.js
  locales/uz.js
  locales/vi.js
  locales/zh.js
Labels: ready to merge

#405 Fix blank color in firefox
  docs/feedback.html
  manifest.json
  script.js
Labels: ready to merge, bug fixes

#407 Reduced height of Search Dropdown
  style.css
Labels: ready to merge

#413 Year changed
  LICENSE
  README.md
  docs/feedback.html
  index.html
  languages.js
  manifest(firefox).json
  manifest.json
  script.js
  style.css
Labels: ready to merge, bug fixes, docs

#416 Update chrome store branch
  docs/feedback.html
  script.js
  style.css
Labels: ready to merge

#424 Added Claude to AI tools
  index.html
  languages.js
  locales/az.js
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/es.js
  locales/fr.js
  locales/hi.js
  locales/idn.js
  locales/it.js
  locales/mr.js
  locales/pt.js
  locales/ru.js
  locales/sl.js
  locales/tr.js
  locales/uz.js
  locales/vi.js
  locales/zh.js
Labels: ready to merge

#426 Updated README.md
  README.md
Labels: ready to merge, docs

#420 Added Hungarian language
  README.md
  index.html
  languages.js
  locales/hu.js
  script.js
  tools/languagesAnalysis.html
Labels: ready to merge, i18n / l10n

#428 Changed Weather retention time and download section of Readme.md
  README.md
  docs/Loading.png
  index.html
  script.js
  shortcuts_icons/.DS_Store
  svgs/.DS_Store
  svgs/shortcuts_icons/adobe-firefly.svg
  svgs/shortcuts_icons/bard.svg
  svgs/shortcuts_icons/chatgpt.svg
  svgs/shortcuts_icons/email.svg
  svgs/shortcuts_icons/facebook.svg
  svgs/shortcuts_icons/feedback.svg
  svgs/shortcuts_icons/github-shortcut.svg
  svgs/shortcuts_icons/github.svg
  svgs/shortcuts_icons/instagram.svg
  svgs/shortcuts_icons/invalid-url.svg
  svgs/shortcuts_icons/offline.svg
  svgs/shortcuts_icons/reddit.svg
  svgs/shortcuts_icons/telegram.svg
  svgs/shortcuts_icons/twitter.svg
  svgs/shortcuts_icons/whatsApp.svg
  svgs/shortcuts_icons/youtube.svg
  svgs/todo-check-fill.svg
  svgs/todo-check-stroke.svg
Labels: ready to merge, enhancement, docs

#429 Massive Code Cleanup - pt1
  background.js
  index.html
  locales/README.md
  scripts/README.md
  scripts/languages.js
  scripts/preload.js
  scripts/script.js
Labels: ready to merge, enhancement, docs

#403 Fixed the Quotes Issue
  index.html
  manifest.json
  quotes.js
  script.js
  style.css
Labels: ready to merge, bug fixes

#445 Update README.md
  README.md
  index.html
  locales/bn.js
  locales/en.js
  locales/hi.js
  locales/hu.js
  locales/it.js
  locales/pt.js
  locales/tr.js
  scripts/languages.js
  scripts/preload.js
Labels: ready to merge, i18n / l10n, docs

#448 Updated PR template and fixed link
  .github/pull_request_template.md
  README.md
Labels: ready to merge, docs

#458 Fix GPS error fallback
  docs/Get_WeatherAPI_Key.html
  scripts/script.js
Labels: ready to merge, bug fixes, docs

#432 Added back zoom slider
  index.html
  preload.js
  script.js
  style.css
Labels: ready to merge, enhancement

#443 Update vi.js
  README.md
  locales/vi.js
  scripts/script.js
  style.css
Labels: ready to merge, i18n / l10n

#450 Fix: Hide Mic Icon Visibility
  scripts/script.js
  style.css
Labels: ready to merge, bug fixes

#452 feat: add translation - np (Nepali)
  README.md
  index.html
  locales/np.js
  scripts/languages.js
  scripts/script.js
  tools/languagesAnalysis.html
Labels: ready to merge, i18n / l10n

#454 White/Black Border Fixes
  scripts/script.js
  style.css
Labels: ready to merge, bug fixes

#456 New translations added
  locales/fr.js
Labels: ready to merge, i18n / l10n

#444 Massive Code Cleanup - pt2
  index.html
  scripts/ai-tools.js
  scripts/google-app-menu.js
  scripts/save-load-states.js
  scripts/script.js
Labels: ready to merge, enhancement

#461 Updated italian
  locales/it.js
Labels: ready to merge, i18n / l10n

#453 Fix/responsiveness
  index.html
  locales/en.js
  scripts/languages.js
  scripts/script.js
  style.css
Labels: ready to merge, enhancement, bug fixes

#462 Massive Code Cleanup - pt3 (bookmarks and added TODOs)
  index.html
  scripts/bookmarks.js
  scripts/script.js
Labels: ready to merge, refactor

#466 l10n: Update Czech translation
  locales/cs.js
Labels: ready to merge, i18n / l10n

#467 Fixed User Text Position
  style.css
Labels: ready to merge, enhancement, bug fixes

#488 Update IDN Translation
  locales/idn.js
Labels: ready to merge, i18n / l10n

#477 Updated Adaptive Icon css for Better Favicon Visibility
  scripts/script.js
Labels: ready to merge, enhancement

#470 Code splitting: Clock
  index.html
  scripts/clock.js
  scripts/script.js
Labels: ready to merge, refactor

#463 Code Splitting: Voice search, wallpaper, backup restore settings
  index.html
  scripts/backup-restore.js
  scripts/script.js
  scripts/voice-search.js
  scripts/wallpaper.js
Labels: ready to merge, refactor

#475 Update translations (hi and bn)
  index.html
  locales/az.js
  locales/bn.js
  locales/cs.js
  locales/en.js
  locales/es.js
  locales/fr.js
  locales/hi.js
  locales/hu.js
  locales/idn.js
  locales/it.js
  locales/ja.js
  locales/ko.js
  locales/mr.js
  locales/np.js
  locales/pt.js
  locales/ru.js
  locales/sl.js
  locales/tr.js
  locales/uz.js
  locales/vi.js
  locales/zh.js
  scripts/script.js
Labels: ready to merge, i18n / l10n

#469 Code splitting: ToDo list
  index.html
  scripts/google-app-menu.js
  scripts/script.js
  scripts/todo-list.js
Labels: ready to merge, refactor

#483 Fix keydown event for Search engines dropdown
  manifest(firefox).json
  manifest.json
  scripts/script.js
Labels: ready to merge, enhancement, bug fixes

#465 Dark Mode for All Existing Color Themes
  index.html
  locales/en.js
  scripts/languages.js
  scripts/script.js
  scripts/wallpaper.js
  style.css
Labels: ready to merge, enhancement

#492 Firefox Custom Color Theme Fix
  script.js
Labels: ready to merge, bug fixes

#493 Refactored Color Picker and Changed Shades for custom color
  scripts/script.js
  style.css
Labels: ready to merge, refactor

#494 Code Split: Weather, UserText, browser-utils
  images/Loading.png
  index.html
  manifest(firefox).json
  scripts/ai-tools.js
  scripts/background.js
  scripts/backup-restore.js
  scripts/bookmarks.js
  scripts/browser-utils.js
  scripts/clock.js
  scripts/custom-text.js
  scripts/google-apps.js
  scripts/languages.js
  scripts/preload.js
  scripts/script.js
  scripts/voice-search.js
  scripts/wallpaper.js
  scripts/weather.js
Labels: ready to merge, refactor

#496 Changed Grey theme name to Peach theme and Improved CSS code
  favicon/grey.png
  favicon/peach.png
  index.html
  scripts/script.js
  style.css
Labels: ready to merge, enhancement

#497 Fixed Shortcuts Title Overflow
  style.css
Labels: ready to merge, bug fixes

#499 New language translation: Traditional Chinese
  README.md
  index.html
  locales/zh_TW.js
  scripts/clock.js
  scripts/languages.js
  tools/languagesAnalysis.html
Labels: ready to merge, enhancement, i18n / l10n

#500 Fixed AM/PM Display Error
  scripts/clock.js
Labels: ready to merge, bug fixes

#502 Removed unnecessary code from quotes.js
  quotes.js
Labels: ready to merge, refactor

#495 Enabled vertical scroll for horizontal movement in AI Tools
  scripts/ai-tools.js
  scripts/script.js
Labels: ready to merge, enhancement
